### ISSUE TITLE
Image umount delets image if the mountpoint is busy

### ISSUE THREAD

**Issue by michaelhoehl** [bluebanquise/tools#10]
We found a bug with the disklessset tool.
Scenario:
1. You mount an image via disklessset to (/var/tmp/diskless/workdir/_imagename_/mnt)
2. Exit disklessset or use another terminal and change directory to /var/tmp/diskless/workdir/_imagename_/mnt for chroot or whatever
3. You then start again disklessset to umount the image (and still have a bash in the mountpoint)

In this scenario the disklessset tool failed to umount the image, because the mountpoint is busy, but it still proceed with the umount process. So it will still do an "rm -rf /var/tmp/diskless/workdir/_imagename_/mnt " which will delete the content of the image. Afterwards disklessset will crash, but the image is already lost.

Solution would be just to check if the umount was successfully before executing the rm -rf command. 

There is also typo in the menu for umounting:
 3 - **Unount** an existing livenet image ->  3 - Umount an existing livenet image

**Comment by oxedions** [comment]
Dear @michaelhoehl 

Thanks a lot for reporting this issue ! 🙂 

I will investigate this issue asap !

**Comment by oxedions** [comment]
Issue has been solved in latest release :-)
